# This is a basic workflow to help you get started with Actions

name: fristname 


on: workflow_dispatch


jobs:
  frist-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print getting
        run:  echo"ssss"
      - name: bye_ssjsj
        run:  echo"bye"
